version: '3'

services:

  # flask app service
  flask-app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
   